float:
  any:
  - base_args: ['@metric', '@dimension']
    constructor: VsagHGraph
    disabled: false
    docker_tag: ann-benchmarks-vsag
    module: ann_benchmarks.algorithms.vsag
    name: hgraph(vsag)
    run_groups:
      HGraph:
        args:
          max_degree: [16, 32, 48, 64]
          ef_construction: 400
          alpha: [1.0, 1.2]
        query_args: [[10, 20, 30, 40, 60, 80, 120, 200, 400, 600, 800]]
  - base_args: ['@metric', '@dimension']
    constructor: VsagHNSW
    disabled: false
    docker_tag: ann-benchmarks-vsag
    module: ann_benchmarks.algorithms.vsag
    name: hnsw(vsag)
    run_groups:
      HNSW:
        args:
          M: [8, 12, 16, 24, 32, 36, 48, 64]
          ef_construction: 300
          use_int8: [4, 8]
          rs: [0, 0.3, 0.5, 1]
        query_args: [[10, 20, 30, 40, 60, 80, 120, 200, 400, 600, 800]]
